# Generated by Django 4.2.3 on 2023-07-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='name',
            field=models.CharField(default='placeholder_name', max_length=200),
            preserve_default=False,
        ),
    ]
