# Generated by Django 4.2.3 on 2023-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_phonenumber_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='int_phone',
            field=models.IntegerField(null=True),
        ),
    ]
